services:
  app:
    build: .
    container_name: google-ads-campaign-creator
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      BASE_PATH: ${BASE_PATH}
      PUBLIC_URL: ${PUBLIC_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_ADS_CLIENT_ID: ${GOOGLE_ADS_CLIENT_ID}
      GOOGLE_ADS_CLIENT_SECRET: ${GOOGLE_ADS_CLIENT_SECRET}
      GOOGLE_ADS_DEVELOPER_TOKEN: ${GOOGLE_ADS_DEVELOPER_TOKEN}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      sharednet:
    
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: google-ads-campaign-creator-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: google-ads-campaign-creator
      POSTGRES_PASSWORD: NM3103LLK6
      POSTGRES_DB: google-ads-campaign-creator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      sharednet:
        aliases:
          - google-ads-campaign-creator-db

networks:
  sharednet:
    external: true

volumes:
  postgres_data:
    name: google-ads-campaign-creator-postgres-data
